const countries ={
    "am-ET" : "Amharic",
    "ar-SA" :"Arabic",
    "en-US": "English",
    "be-BY" :"Bemba" ,
    "bg-BG":"Bulgarian ",
    "bn-BD":"Bangla",
    "bs-BA":"Bosnian",
    "ca-ES":"Catalan",
    "cs-CZ":"Czech",
    "da-DK":"Danish",
    "de-DE":"German",
    "el-GR":"Greek",
    "es-AR":"Spanish (Argentina)",
    "et-EE":"Estonian",
    "fa-IR":"Persian",
    "fi-FI":"Finnish",
    "fr-FR":"French",
    "gu-IN":"Gujarati",
    "he-IL":"Hebrew",
    "hi-IN":"Hindi",
    "hr-HR":"Croatian",
    "hu-HU":"Hungarian",
    "id-ID":"Indonesian",
    "it-IT":"Italian",
    "ja-JP":"Japanese",
    "kn-IN":"Kannada",
    "ko-KR":"Korean",
    "lt-LT":"Lithuanian",
    "lv-LV":"Latvian",
    "ml-IN":"Malayalam",
    "mr-IN":"Marathi",
    "ne-NP":"Nepali",
    "nl-NL":"Dutch",
    "no-NO":"Norwegian",
    "pa-IN":"Punjabi",
    "pl-PL":"Polish",
    "pt-BR":"Portuguese(Brazil)",
    "pt-PT":"Portuguese(Portugal)",
    "ro-RO":"Romanian",
    "ru-RU":"Russian",
    "sk-SK":"Slovak",
    "sl-SI":"Slovenian",
    "sr-RS":"Serbian",
    "sv-SE":"Swedish",
    "ta-IN":"Tamil",
    "te-IN":"Telugu",
    "th-TH":"Thai",
    "tr-TR":"Turkish",
    "uk-UA":"Ukrainian",
    "ur-PK":"Urdu",
    "vi-VN":"Vietnamese",
    "zh-CN":"Chinese Simplified"
    };

export default countries;